### ISSUE TITLE
 Could not parse rfc1738 URL from string

### ISSUE THREAD

**Issue by foocp** [dataquestio/twitter-scrape#2]
I have all the requirements, running python3.5.3 in virtualenvwrapper, on the most recent Raspbian Stretch (Jan2018), but I always get this. Any hints?

```
Traceback (most recent call last):
  File "scraper.py", line 8, in <module>
    db = dataset.connect(settings.CONNECTION_STRING)
  File "/home/pi/.virtualenvs/testtwitter_scrape/lib/python3.5/site-packages/dataset/__init__.py", line 41, in connect
    ensure_schema=ensure_schema, row_type=row_type)
  File "/home/pi/.virtualenvs/testtwitter_scrape/lib/python3.5/site-packages/dataset/database.py", line 53, in __init__
    self.engine = create_engine(url, **engine_kwargs)
  File "/home/pi/.virtualenvs/testtwitter_scrape/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/pi/.virtualenvs/testtwitter_scrape/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 50, in create
    u = url.make_url(name_or_url)
  File "/home/pi/.virtualenvs/testtwitter_scrape/lib/python3.5/site-packages/sqlalchemy/engine/url.py", line 205, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/pi/.virtualenvs/testtwitter_scrape/lib/python3.5/site-packages/sqlalchemy/engine/url.py", line 254, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''
```

**Comment by elilienstein** [comment]
I had a similar error and solved it by setting  CONNECTION_STRING = 'sqlite:///tweets.db'. 
My python version is 2.7
I am having other problems getting this to run, but not that particular error.

**Comment by foocp** [comment]
that fixed this, thanks! a stupid copy and paste error.

Btw, if dump.py throws this error
`AttributeError: module 'dataset' has no attribute 'freeze'`
see here for a solution. The module has changed since 2016. [https://stackoverflow.com/questions/48090148/no-freeze-attribute-when-using-dataset-module-in-python](https://stackoverflow.com/questions/48090148/no-freeze-attribute-when-using-dataset-module-in-python)

**Comment by DennisFaucher** [comment]
My entry in private.py looks to be spelled correctly but I am also having this RFC errors. Any ideas? TIA.

CONNECTION_STRING = ”sqlite:///tweets.db”

**Comment by DennisFaucher** [comment]
Changed double quotes to single quotes and error went away. Interesting.

**Comment by laurianops** [comment]
Problem: I played with Pandas and Postgres yesterday and today I had the same problem.
Solution:
my method --> dado.to_sql(name='pessoa', con=engine, if_exists='append', index=False)
the parameter cannot have <'>, I remove the quotes and bingo !!! it worked out .

**Comment by ryanmsnyder** [comment]
@LaurianoElmiroDuarte what did you remove the quotes from?
